"""add image, observacion, and tipo_movimiento

Revision ID: 3e9436e2a447
Revises: fd404ea84aba
Create Date: 2026-03-24 15:42:58.948157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9436e2a447'
down_revision = 'fd404ea84aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observacion', sa.Text(), nullable=True))

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_movimiento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_column('tipo_movimiento')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('observacion')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
