"""add price_approvals table

Revision ID: a786cd586f83
Revises: fda4d956d6a5
Create Date: 2026-04-19 19:37:02.193788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a786cd586f83'
down_revision = 'fda4d956d6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_exchanges')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('consecutivo')
        batch_op.drop_column('cliente_nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consecutivo', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('product_exchanges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_returned_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variant_returned_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_new_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variant_new_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('excedente_pagado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('metodo_pago_excedente', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('product_exchanges_admin_id_fkey')),
    sa.ForeignKeyConstraint(['product_new_id'], ['products.id'], name=op.f('product_exchanges_product_new_id_fkey')),
    sa.ForeignKeyConstraint(['product_returned_id'], ['products.id'], name=op.f('product_exchanges_product_returned_id_fkey')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('product_exchanges_sale_id_fkey')),
    sa.ForeignKeyConstraint(['variant_new_id'], ['product_variants.id'], name=op.f('product_exchanges_variant_new_id_fkey')),
    sa.ForeignKeyConstraint(['variant_returned_id'], ['product_variants.id'], name=op.f('product_exchanges_variant_returned_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_exchanges_pkey'))
    )
    # ### end Alembic commands ###
