"""Added pricing to variants

Revision ID: e060e044710c
Revises: daab7a816897
Create Date: 2026-04-06 16:41:40.316492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e060e044710c'
down_revision = 'daab7a816897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_costo', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_minimo', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_sugerido', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('precio_sugerido')
        batch_op.drop_column('precio_minimo')
        batch_op.drop_column('precio_costo')

    # ### end Alembic commands ###
