"""Agregar campos producto manual a sale_details

Revision ID: fda4d956d6a5
Revises: 22b369c56cef
Create Date: 2026-04-13 19:09:41.510519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda4d956d6a5'
down_revision = '22b369c56cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_manual', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('precio_costo_manual', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('precio_costo_manual')
        batch_op.drop_column('nombre_manual')

    # ### end Alembic commands ###
